[build]
  command = """
  ./bin/deploy.sh
  """
  publish = "_site/"

[build.environment]
  MISE_RUBY_COMPILE = "false"

[context.deploy-preview]
  command = """
  ./bin/deploy.sh $DEPLOY_PRIME_URL
  """

[[plugins]]
package = "netlify-plugin-submit-sitemap"
