[build]
  command = """
  ./_auto/deploy.sh
  """
  publish = "_site/"

[context.deploy-preview]
  command = """
  # Replace the Deploy URL with the Preview URL
  sed -i "/url\:/curl\: $DEPLOY_PRIME_URL" _config.yml
  ./_auto/deploy.sh
  """

[[plugins]]
package = "netlify-plugin-submit-sitemap"
