[build]
  command = """
  git submodule update --remote
  pip install -r requirements.txt
  python _auto/latest.py
  bundle exec jekyll build
  """
  publish = "_site/"

[context.deploy-preview]
  command = """
  printf "url: %s" "$DEPLOY_PRIME_URL" > _config_netlify.yml
  git submodule update --remote
  pip install -r requirements.txt
  python _auto/latest.py
  bundle exec jekyll build --config _config.yml,_config_netlify.yml
  """

[[plugins]]
package = "netlify-plugin-submit-sitemap"
