name: Lighthouse CI
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Wait for the Netlify Preview
        uses: jakepartusch/wait-for-netlify-action@v1
        id: netlify
        with:
          site_name: 'endoflife-date'
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v8
        with:
          urls: |
            ${{ steps.netlify.outputs.url }}/django
