name: Lint

on:
  workflow_dispatch: # Manually run workflow.
  push:
    branches: ["master", "release"]
  pull_request:
    branches: ["master", "release"]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: 20
          cache: "npm"

      - name: Setup ruby
        uses: ruby/setup-ruby@dffb23f65a78bba8db45d387d5ea1bbd6be3ef18 # v1
        with:
          bundler-cache: true

      - name: Build site
        run: bundle exec jekyll build

      - name: Validate OpenAPI specification
        run: npx @quobix/vacuum@latest lint --ignore-file .vacuumignore.yml --details --no-style --no-banner --all-results _site/docs/api/v1/openapi.yml

      - name: Validate Markdown files
        run: npx markdownlint-cli2@latest '**/*.md' '!node_modules' '!vendor'
        continue-on-error: true

      - name: Validate Formatting
        run: npx prettier@latest --check .
        continue-on-error: true
